/// <reference path="../.astro/types.d.ts" />
/// <reference path="../worker-configuration.d.ts" />

// Cloudflare bindings (Env, the cloudflare:workers module, and the global Env
// alias) are generated by `wrangler types` into worker-configuration.d.ts,
// driven by wrangler.jsonc. Run `pnpm types` after changing wrangler.jsonc.

interface StreamPlayer {
  currentTime: number;
  duration: number;
  paused: boolean;
  muted: boolean;
  volume: number;
  addEventListener(event: string, handler: () => void): void;
  removeEventListener(event: string, handler: () => void): void;
  play(): Promise<void>;
  pause(): void;
}

declare global {
  interface Window {
    Stream?: (iframe: HTMLIFrameElement) => StreamPlayer;
  }
}

export {};
